name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.json'
      - 'tox.ini'
      - '.github/workflows/maintests.yml'
      - '.github/workflows/prtests.yml'
      - '.pre-commit-config.yaml'
      - 'scripts/requirements.txt'
      - 'scripts/requirements.dev.txt'
jobs:
  no_extra_fields:
    env:
      HORDELIB_CI_ONGOING: "1"
      TESTS_ONGOING: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r scripts/requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run unit tests
        run: tox -e no-extra-fields
  build:
    env:
      TESTS_ONGOING: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r scripts/requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run validation
        run: tox -e validate-sd
